# Generated by Django 2.2.5 on 2022-03-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NasdaqDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('depth', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nasdaq_depth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NasdaqIndex3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, null=True)),
                ('index', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nasdaq_index_3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NasdaqIndex7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nasdaq_index_7',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NasdaqSpo3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(blank=True, max_length=255, null=True)),
                ('p', models.CharField(blank=True, max_length=255, null=True)),
                ('o', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nasdaq_spo_3',
                'managed': False,
            },
        ),
    ]
