# Generated by Django 3.2.5 on 2021-11-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasdaq', '0002_dasdaqdepth'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasdaqSpo3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(blank=True, db_collation='utf8_bin', max_length=255, null=True)),
                ('p', models.CharField(blank=True, db_collation='utf8_bin', max_length=255, null=True)),
                ('o', models.CharField(blank=True, db_collation='utf8_bin', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nasdaq_spo_3',
                'managed': False,
            },
        ),
    ]
